apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-spam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-spam
  template:
    metadata:
      labels:
        app: tg-spam
    spec:
      containers:
        - name: tg-spam
          image: {{ .Values.tgspam.image }}
          env:
            {{- if .Values.tgspam.env }}
            {{- range $key, $value := .Values.tgspam.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
            {{- end }}
            - name: OPENAI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_TOKEN
                  optional: true
          volumeMounts:
            - name: tg-data
              mountPath: {{ .Values.tgspam.volumeMountPath }}
      volumes:
        - name: tg-data
          persistentVolumeClaim:
            claimName: tg-data

