apiVersion: apps/v1
kind: Deployment
metadata:
  name: tg-spam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tg-spam
  template:
    metadata:
      labels:
        app: tg-spam
    spec:
      containers:
        - name: tg-spam
          image: {{ .Values.tgspam.image }}
          env:
            - name: TELEGRAM_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tgspam.secretName }}
                  key: TELEGRAM_TOKEN
            {{- if .Values.tgspam.env }}
            {{- range $key, $value := .Values.tgspam.env }}
            {{- if and (ne $key "TELEGRAM_TOKEN") (ne $key "OPENAI_TOKEN") }}
            - name: {{ $key }}
              value: "{{ $value }}"
            {{- end }}
            {{- end }}
            {{- end }}
            {{- if .Values.tgspam.secretName }}
            - name: OPENAI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.tgspam.secretName }}
                  key: OPENAI_TOKEN
                  optional: true
            {{- end }}
          {{- if and .Values.tgspam.args (gt (len .Values.tgspam.args) 0) }}
          args:
            {{- range .Values.tgspam.args }}
            - {{ . }}
            {{- end }}
          {{- end }}
          volumeMounts:
            - name: tg-data
              mountPath: {{ .Values.tgspam.volumeMountPath }}
      volumes:
        - name: tg-data
          persistentVolumeClaim:
            claimName: tg-data

