apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tg-spam.fullname" . }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "tg-spam.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.storage.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.storage.tgDataSize | quote }}


