apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tg-data
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.tgDataSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reproxy-logs
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.reproxyLogsSize }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: reproxy-ssl
spec:
  accessModes: [ "ReadWriteOnce" ]
  storageClassName: standard
  resources:
    requests:
      storage: {{ .Values.storage.reproxySSLSize }}
