apiVersion: v1
kind: Service
metadata:
  name: reproxy
spec:
  type: LoadBalancer
  selector:
    app: reproxy
  ports:
    {{- range .Values.reproxy.ports }}
    - name: {{ .name }}
      port: {{ .port }}
      targetPort: {{ .targetPort }}
    {{- end }}
