tgspam:
  image: ghcr.io/umputun/tg-spam:latest
  env:
    TELEGRAM_TOKEN: ""  # Токен бота от @BotFather
    ADMIN_GROUP: ""
    # Настройки спама и прочее
    MAX_EMOJI: "3"
    META_LINKS_LIMIT: "3"
    META_USERNAME_SYMBOLS: "@"
    NO_SPAM_REPLY: "true"
    MIN_MSG_LEN: "10"
    DEBUG: "true"
    MULTI_LANG: "2"
    META_KEYBOARD: "true"
  volumeMountPath: /var/srv/data

storage:
  tgDataSize: 1Gi


